name: receive_sharing
description: A new Flutter project.
version: 0.0.1
homepage: https://github.com/kodal/receive_sharing

environment:
  sdk: '>=2.19.2 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  plugin:
    platforms:
      android:
        package: com.kodal.receive_sharing
        pluginClass: ReceiveSharingPlugin
      ios:
        pluginClass: ReceiveSharingPlugin
      web:
        pluginClass: ReceiveSharingWeb
        fileName: receive_sharing_web.dart